name: Forex Pending-Order Bot

on:
  # Hourly for 06:00–18:00 Asia/Bangkok (UTC+7) → 23:00–11:00 UTC
  schedule:
    - cron: "*/30 * * * *"   # ทุกครึ่งชั่วโมงทั้งวัน
  workflow_dispatch: {}

# allow pushing changes back to the repo
permissions:
  contents: write

concurrency:
  group: forex-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    env:
      PYTHONUNBUFFERED: "1"
      TRADING_TZ: "Asia/Bangkok"
      DEFAULT_SPREAD_PIPS: "1.0"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TYPHOON_API_KEY: ${{ secrets.TYPHOON_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
      IQ_USER: ${{ secrets.IQ_USER }}
      IQ_PASS: ${{ secrets.IQ_PASS }}

    steps:
      - name: Checkout (track default branch, non-detached)
        uses: actions/checkout@v4
        with:
          # checkout the default branch so we can push back to it
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ms-playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ms-playwright-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -U git+https://github.com/iqoptionapi/iqoptionapi.git@7.1.1

      - name: Install Playwright (Chromium) + system deps
        run: |
          python -m playwright install --with-deps chromium

      - name: Run bot (one shot)
        run: |
          python new_forex.py --mode auto

      - name: Commit & push changes in data/ (if any)
        if: always()
        run: |
          set -e
          # Ensure we are on a named branch (not detached)
          BRANCH=$(git branch --show-current)
          if [ -z "$BRANCH" ]; then
            BRANCH="${{ github.event.repository.default_branch }}"
            git checkout "$BRANCH"
          fi

          # Pull latest and rebase to avoid conflicts
          git config pull.rebase true
          git pull --rebase origin "$BRANCH" || true

          # Configure committer
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add only data/ changes (ignore other files)
          if [ -d "data" ]; then
            if [ -n "$(git status --porcelain data/)" ]; then
              git add data/
              git commit -m "chore(data): update ledger/artifacts [skip ci]"
              git push origin HEAD:"$BRANCH"
              echo "✅ Pushed updated data/"
            else
              echo "ℹ️ No changes in data/; nothing to commit."
            fi
          else
            echo "ℹ️ data/ not found; nothing to commit."
          fi
